#### Step1: Data Load

In [3]:
import pandas as pd
data = pd.read_csv('weight_height.csv')

In [4]:
data.shape

(10000, 3)

In [5]:
data.head()

Gender     Height      Weight
0   Male  73.847017  241.893563
1   Male  68.781904  162.310473
2   Male  74.110105  212.740856
3   Male  71.730978  220.042470
4   Male  69.881796  206.349801

In [6]:
data.Gender = [1 if g=="Male" else 0 for g in data.Gender]
data.head()

Gender     Height      Weight
0       1  73.847017  241.893563
1       1  68.781904  162.310473
2       1  74.110105  212.740856
3       1  71.730978  220.042470
4       1  69.881796  206.349801

#### Step2: Separate input data and output
       Data and Labels 

In [7]:
X = data[['Height']]
y = data[['Weight']]

#### Step3: Split Data Training data and Testing Data

In [8]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test   = train_test_split(X,y,random_state=0, test_size=.40)

In [9]:
X_train

Height
7809  64.494318
5279  58.987139
3279  65.682365
8984  62.935048
8466  62.218599
...         ...
9225  60.421255
4859  66.730755
3264  67.467086
9845  62.127480
2732  70.597025

[6000 rows x 1 columns]

In [10]:
import random

In [11]:
random.seed(5566)
random.randint(1,100)

85

# Step:4 Model Selection

In [12]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()

# Step:5 Model Training (Fit Karna)

In [13]:
# supervised learning data+ans
model.fit(X_train,y_train)

LinearRegression()

In [14]:
model.coef_

array([[7.71316805]])

In [15]:
model.intercept_

array([-350.4837037])

# Step6: Prediction on Training Data

In [16]:
y_pred_train = model.predict(X_train)

In [17]:
y_train.values.reshape(6000,)

array([141.8754655, 100.743008 , 186.2707727, ..., 162.4759573,
       136.7830224, 188.4506741])

In [18]:
y_pred_train.reshape(6000,)

array([146.97181036, 104.4940115 , 156.13541212, ..., 169.9012675 ,
       128.71599066, 194.04300997])

In [19]:
pd.DataFrame({"y_train":y_train.values.reshape(6000,), "y_pred":y_pred_train.reshape(6000,) })

y_train      y_pred
0     141.875465  146.971810
1     100.743008  104.494011
2     186.270773  156.135412
3     124.460003  134.944897
4     130.012336  129.418808
...          ...         ...
5995   97.263881  115.555590
5996  174.156893  164.221820
5997  162.475957  169.901267
5998  136.783022  128.715991
5999  188.450674  194.043010

[6000 rows x 2 columns]

In [20]:
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

In [21]:
r2_score(y_train,y_pred_train)

0.8570169896550387

In [22]:
mean_absolute_error(y_train,y_pred_train)

9.67884817077144

# Step7: Prediction on Test  Data 

In [23]:
y_pred_test = model.predict(X_test)

In [24]:
r2_score(y_test,y_pred_test)

0.8523953836639468

In [25]:
mean_absolute_error(y_test,y_pred_test)

9.848520352275886

In [26]:
def predict1_weight(height):
   return  model.predict(height)*.453592

In [27]:
height = float(input("Enter you height in feet"))
print(f"Your predicted weight is {predict1_weight([[height*12]])} kgs")

Your predicted weight is [[76.1314206]] kgs


c:\Users\User\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


In [28]:
data.Gender = [1 if g=="Male" else 0 for g in data.Gender]
data

Gender     Height      Weight
0          0  73.847017  241.893563
1          0  68.781904  162.310473
2          0  74.110105  212.740856
3          0  71.730978  220.042470
4          0  69.881796  206.349801
...      ...        ...         ...
9995       0  66.172652  136.777454
9996       0  67.067155  170.867906
9997       0  63.867992  128.475319
9998       0  69.034243  163.852461
9999       0  61.944246  113.649103

[10000 rows x 3 columns]

In [29]:
X = data[['Gender', 'Height']]
X

Gender     Height
0          0  73.847017
1          0  68.781904
2          0  74.110105
3          0  71.730978
4          0  69.881796
...      ...        ...
9995       0  66.172652
9996       0  67.067155
9997       0  63.867992
9998       0  69.034243
9999       0  61.944246

[10000 rows x 2 columns]

In [30]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test   = train_test_split(X,y,random_state=13230, test_size=.40)

In [31]:
mlr = LinearRegression()

In [32]:
mlr.fit(X_train, y_train)

LinearRegression()

In [33]:
y_pred_train = mlr.predict(X_train)

In [34]:
r2_score(y_train,y_pred_train)

0.8578885186182372

## Normalization

In [47]:
df=pd.read_csv('advertising.csv')

In [48]:
df.head()

TV  Radio  Newspaper  Sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3   12.0
3  151.5   41.3       58.5   16.5
4  180.8   10.8       58.4   17.9

In [49]:
y=df[['Sales']]

In [50]:
X=df[['TV','Radio','Newspaper']]

In [56]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test  = train_test_split(X,y, test_size=.20, random_state=123)

In [57]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()

In [58]:
lr.fit(X_train,y_train)

LinearRegression()

In [59]:
y_pred_train = lr.predict(X_train)

In [60]:
r2_score(y_train,y_pred_train)

0.8973234846678751

In [61]:
mean_absolute_error(y_train,y_pred_train)

1.2321616398329005

In [62]:
y_pred_test = lr.predict(X_test)
print(r2_score(y_test,y_pred_test))
print(mean_absolute_error(y_test,y_pred_test))

0.9180169996276659
1.2707307309230793


In [51]:
from sklearn.preprocessing import MinMaxScaler

In [52]:
scaler=MinMaxScaler()
scaler.fit(X)
scaled=scaler.fit_transform(X)

In [53]:
columns=scaler.feature_names_in_

In [63]:
X=pd.DataFrame(data=scaled,columns=columns)

In [64]:
X

TV     Radio  Newspaper
0    0.775786  0.762097   0.605981
1    0.148123  0.792339   0.394019
2    0.055800  0.925403   0.606860
3    0.509976  0.832661   0.511873
4    0.609063  0.217742   0.510994
..        ...       ...        ...
195  0.126818  0.074597   0.118734
196  0.316199  0.098790   0.068602
197  0.596212  0.187500   0.053650
198  0.956713  0.846774   0.579595
199  0.782550  0.173387   0.073879

[200 rows x 3 columns]

In [73]:
X_train,X_test,y_train,y_test  = train_test_split(X,y, test_size=.15, random_state=123)

In [74]:
lr.fit(X_train,y_train)

LinearRegression()

In [75]:
y_pred_train = lr.predict(X_train)

In [76]:
r2_score(y_train,y_pred_train)

0.8999862441074555

In [77]:
mean_absolute_error(y_train,y_pred_train)

1.2247944704639584

In [78]:
y_pred_test = lr.predict(X_test)
print(r2_score(y_test,y_pred_test))
print(mean_absolute_error(y_test,y_pred_test))

0.9085980693374476
1.2951521702888078
